apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: airbnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main-app
          image: sandrageorgiev/api:kube
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: kube
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: db-url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_PASSWORD
