apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init-replica-set
  namespace: airbnb
spec:
  template:
    spec:
      containers:
        - name: mongodb-init
          image: mongo
          command: ["sh", "-c", "mongo --host mongodb-0.mongodb-service:27017 --eval 'rs.initiate({ _id: \"rs0\", members: [ { _id: 0, host: \"mongodb-0.mongodb-service:27017\" }, { _id: 1, host: \"mongodb-1.mongodb-service:27017\" } ] })'"]
      restartPolicy: OnFailure
  backoffLimit: 4
